// ******************** Form Actions **********************//
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_FULFILLED = 'FETCH_QUESTIONS_FULFILLED';
export const FETCH_QUESTIONS_REJECTED = 'FETCH_QUESTIONS_REJECTED';

export const UPDATE_QUESTION = 'UPDATE_QUESTION';

export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_FULFILLED = 'SUBMIT_FORM_FULFILLED';
export const SUBMIT_FORM_REJECTED = 'SUBMIT_FORM_REJECTED';
